# -*- coding: utf-8 -*-
"""pl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mwKOELTeQPrXiWEo8ThU0SiWfavPy7P
"""

import streamlit as st
st.markdown("""
### Modelo que desea usar:
- [Conversión de viajes/día en viajes/hora](#Conversion_de_viajes/dia_en_viajes/hora)
""")
st.header("Módulo 1")
st.subheader("Regresión Lineal y múltiple", divider="violet")

st.subheader("Factor de crecimiento", divider="blue")


st.subheader("Clasificación cruzada", divider="green")
st.subheader("Balanceo de viajes generados y atraídos", divider="yellow")

st.subheader("Conversión de viajes/día en viajes/hora", divider="orange")
vd = st.number_input("Ingresa la cantidad de viajes al día", min_value=0.0)
ph = st.number_input("Ingresa el porcentaje de viajes en la hora que desea determinar", min_value=0.0)
vh= vd*ph
st.write(f"el valor de viaje/hora es  = {vh:.4f}")

st.subheader("Conversión de viajes-persona a viajes-vehículo", divider="red")
vp = st.number_input("Ingresa el valor de viajes persona", min_value=0.0)
opv = st.number_input("Ingresa el valor de ocupacion promedio del vehiculo", min_value=0.01)
vv = vp / opv
st.write(f"el valor de viaje-vehiculo es = {vv:.4f}")

st.header("Módulo 2")
st.subheader("Fratar con una restricción", divider="violet")
st.subheader("Fratar con dos restricción", divider="blue")
st.subheader("Gravedad", divider="green")

st.header("Módulo 3")
st.subheader("Logit binario", divider="yellow")
st.subheader("Logit múltiple", divider="orange")

st.header("Módulo 4")
st.subheader("Asignación todo o nada ", divider="red")
st.subheader("Asignación probabilística (modelo STOCH) ", divider="violet")
st.subheader("Asignación Frank-Wolfe ", divider="blue")

st.header("Módulo 5")
