# -*- coding: utf-8 -*-
"""pl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mwKOELTeQPrXiWEo8ThU0SiWfavPy7P
"""

import streamlit as st
st.markdown("""
### Modelo que desea usar:
- [Regresión Lineal](#regresion-lineal)
""")
st.header("Módulo 1")
st.subheader("Regresión Lineal y múltiple", divider="violet")
st.subheader("Factor de crecimiento", divider="blue")
st.subheader("Clasificación cruzada", divider="green")
st.subheader("Balanceo de viajes generados y atraídos", divider="yellow")
st.subheader("Conversión de viajes/día en viajes/hora", divider="orange")
st.subheader("Conversión de viajes-persona a viajes-vehículo", divider="red")
vp = st.number_input("Ingresa el valor de viajes persona", min_value=0.0)
opv = st.number_input("Ingresa el valor de ocupacion promedio del vehiculo", min_value=0.01)
vv = vp / opv
st.write(f"el valor de viaje por vehiculo es = {vv:.4f}")
