# -*- coding: utf-8 -*-
"""pl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mwKOELTeQPrXiWEo8ThU0SiWfavPy7P
"""

import streamlit as st
st.header("Módulo 1")
st.subheader("Regresión Lineal", divider=True)
st.write(" conversión viaje_persona a viaje_vehiculo")

vp = st.number_input("Ingresa el valor de viajes persona", min_value=0.0)
opv = st.number_input("Ingresa el valor de ocupacion promedio del vehiculo", min_value=0.01)
vv = vp / opv
st.write(f"el valor de viaje por vehiculo es = {vv:.4f}")
